# Generated by Django 3.2.8 on 2021-10-26 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='status bekerja sekarang : ')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildings', models.CharField(max_length=255, verbose_name='Nama Gedung : ')),
                ('tower_name', models.CharField(max_length=255, verbose_name='Nama Tower : ')),
                ('ground_name', models.CharField(max_length=255, verbose_name='Nama Lantai : ')),
                ('job_area', models.CharField(max_length=255, verbose_name='Zona Kerja : ')),
                ('qr_code', models.TextField(default='DTiGVXKFqE9fM7nh', verbose_name='unique code QR')),
                ('qr_img', models.FileField(blank=True, null=True, upload_to='qr/', verbose_name='QR Code Image')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=255, unique=True, verbose_name='NIK : ')),
                ('is_employee', models.BooleanField(default=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('shift', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=255, verbose_name='nomor telepon : ')),
                ('profile_img', models.FileField(upload_to='profile/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Unknown')], default='X', max_length=10)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workingstatus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_permission', models.BooleanField(default=False)),
                ('estimated_time', models.IntegerField(default=0, verbose_name='lama waktu pengerjaan : ')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('on_progress', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('img_before', models.FileField(blank=True, upload_to='assignment/before/')),
                ('img_after', models.FileField(blank=True, upload_to='assignment/after/')),
                ('assignment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.workplace')),
                ('worker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
