# Generated by Django 3.2.8 on 2021-10-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211028_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcontrol',
            name='assignment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.workplace', verbose_name='Tugas yang akan diberikan : '),
        ),
        migrations.AlterField(
            model_name='assignmentcontrol',
            name='estimated_time',
            field=models.IntegerField(default=0, verbose_name='Lama waktu pengerjaan : '),
        ),
        migrations.AlterField(
            model_name='assignmentcontrol',
            name='for_day',
            field=models.DateField(verbose_name='Untuk dikerjakan pada tanggal : '),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.TextField(default='7MZ9VIdamDglSQ6k', verbose_name='unique code QR'),
        ),
    ]
