# Generated by Django 3.2.8 on 2021-10-28 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auto_20211028_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcontrol',
            name='given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.TextField(default='6f5ShiLW8dYHNQm2', verbose_name='unique code QR'),
        ),
    ]
