# Generated by Django 3.2.8 on 2021-10-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211029_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.TextField(default='TkYisjQeaon8dvt9', verbose_name='unique code QR'),
        ),
    ]
