# Generated by Django 3.2.8 on 2021-10-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_workplace_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemanagement',
            name='code',
            field=models.CharField(default='', max_length=255, verbose_name='kode spv'),
        ),
        migrations.AlterField(
            model_name='assignmentcontrol',
            name='estimated_time',
            field=models.IntegerField(default=0, verbose_name='Lama waktu pengerjaan <small class=text-muted> dalam menit </small> : '),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.TextField(default='6s2EeCLqvMya3wjt', verbose_name='unique code QR'),
        ),
    ]
