# Generated by Django 3.2.8 on 2021-10-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211030_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.TextField(default='THkeLU9CmrYGbawz', verbose_name='unique code QR'),
        ),
    ]
