# Generated by Django 3.2.8 on 2021-11-01 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_workplace_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='list tugas : ')),
            ],
        ),
        migrations.AlterField(
            model_name='employeemanagement',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='kode spv'),
        ),
        migrations.AlterField(
            model_name='employeemanagement',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dashboard.workingstatus'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.TextField(default='W3zoi5qLOr0dMlx9', verbose_name='unique code QR'),
        ),
        migrations.CreateModel(
            name='AssignmentListControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.assignmentlist')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.assignmentcontrol')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentlist',
            name='for_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workplace', verbose_name='untuk kerjaan : '),
        ),
    ]
