# Generated by Django 3.2.8 on 2021-11-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211101_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentlistcontrol',
            old_name='control',
            new_name='assignment_control',
        ),
        migrations.RenameField(
            model_name='assignmentlistcontrol',
            old_name='assignment',
            new_name='assignment_list',
        ),
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.TextField(default='VR4vZleHkjafcX5y', verbose_name='unique code QR'),
        ),
    ]
