# Generated by Django 3.2.8 on 2021-11-06 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20211101_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcontrol',
            name='assignment_unique_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='unique_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.TextField(default='mBbiNjayEcshqk2C', verbose_name='unique code QR'),
        ),
    ]
