# Generated by Django 3.2.8 on 2021-11-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20211106_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcontrol',
            name='assignment_unique_id',
            field=models.SlugField(max_length=255, verbose_name='unique_id'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.TextField(default='Uye7oBp3TdnG4rQJ', verbose_name='unique code QR'),
        ),
    ]
