# Generated by Django 3.2.8 on 2021-11-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20211106_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentcontrol',
            old_name='assignment_unique_id',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='employeemanagement',
            name='code',
            field=models.CharField(blank=True, default='BqzQA7UV', max_length=255, verbose_name='kode spv'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.TextField(default='KzPbNq8aChk9DpIg', verbose_name='unique code QR'),
        ),
    ]
