# Generated by Django 3.2.8 on 2021-11-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20211107_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcontrol',
            name='img_after',
            field=models.FileField(blank=True, null=True, upload_to='assignment/after/'),
        ),
        migrations.AlterField(
            model_name='assignmentcontrol',
            name='img_before',
            field=models.FileField(blank=True, null=True, upload_to='assignment/before/'),
        ),
        migrations.AlterField(
            model_name='employeemanagement',
            name='code',
            field=models.CharField(blank=True, default='OiVBJYWC', max_length=255, verbose_name='kode spv'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.TextField(default='YRmGecU3L1pNhgJ6', verbose_name='unique code QR'),
        ),
    ]
