# Generated by Django 3.2.8 on 2021-11-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20211118_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemanagement',
            name='code',
            field=models.CharField(blank=True, default='7BYZtnXl', max_length=255, verbose_name='kode spv'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.TextField(default='siYlymNGw17Mqzou', verbose_name='unique code QR'),
        ),
    ]
