# Generated by Django 3.2.8 on 2021-11-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20211127_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemanagement',
            name='code',
            field=models.CharField(blank=True, default='5HzlwocK', max_length=255, verbose_name='kode spv'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.SlugField(verbose_name='unique code QR'),
        ),
    ]
