# Generated by Django 3.2.8 on 2021-11-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20211130_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcontrol',
            name='uid',
            field=models.SlugField(max_length=255, unique=True, verbose_name='unique_id'),
        ),
        migrations.AlterField(
            model_name='employeemanagement',
            name='code',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='kode spv'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='qr_code',
            field=models.SlugField(unique=True, verbose_name='unique code QR'),
        ),
    ]
